# Generated by Django 4.0.3 on 2022-03-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studentdetail_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='address',
            new_name='current_address',
        ),
        migrations.RenameField(
            model_name='studentdetail',
            old_name='marks',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='studentdetail',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='gender',
            field=models.CharField(default='anonymous', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='nationality',
            field=models.CharField(default='anonymous', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='permamemt_address',
            field=models.CharField(default='anonymous', max_length=50),
            preserve_default=False,
        ),
    ]
