# Generated by Django 4.0.3 on 2022-03-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_address_studentdetail_current_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='permamemt_address',
            new_name='permanent_address',
        ),
    ]
