# Generated by Django 4.0.4 on 2022-05-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_permamemt_address_studentdetail_permanent_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.IntegerField(default=30)),
                ('branch', models.CharField(max_length=30)),
                ('yearsofstudy', models.IntegerField(default=10)),
                ('mobile_number', models.IntegerField(default=200)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('current_address', models.CharField(max_length=50)),
                ('permanent_address', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
    ]
