# Generated by Django 4.0.4 on 2022-05-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.IntegerField(default=30)),
                ('branch', models.CharField(max_length=30)),
                ('yearsofstudy', models.IntegerField(default=10)),
                ('mobile_number', models.IntegerField(default=200)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
